typography_spectrum: 0.9116067313589156
color:
  brandStrength: 0.363936526235193
  lightness: 0.7666099148336798
  saturation: 0.9262934853322804
  rhythmicContrast: 0.12566022528335452
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
layout_spectrum: 0.40248515852726996
name: QueerMenno
title: QueerMenno
